exp_name: exp_001
seed: 3090
input_dir: ../data/raw_data
pseudo_dir: ../output/preprocess/
n_splits: 5
thresholds: 
  - 95
  - 90
  - 87
  - 86.99
  - 85
epoch: 1000
trainer:
  # accelerator: cpu
  gpus: 1
  accumulate_grad_batches: 1
  progress_bar_refresh_rate: 1
  fast_dev_run: False
  num_sanity_val_steps: 0
  resume_from_checkpoint: # None
transform:
    name: get_default_transforms
    image_size: 224
train_loader:
  batch_size: 256
  shuffle: True
  num_workers: 8
  pin_memory: False
  drop_last: True
val_loader:
  batch_size: 256
  shuffle: False
  num_workers: 8
  pin_memory: False
  drop_last: False
model:
  name: swin_tiny_patch4_window7_224
  output_dim: 1
optimizer:
    name: optim.AdamW
    params:
      lr: 0.00005
scheduler:
    name: optim.lr_scheduler.CosineAnnealingWarmRestarts
    params:
      T_0: 20
      eta_min: 0.0001
earlystopping:
  monitor: val_loss
  mode: min  
  patience: 4
ckpt:
  filename: best_loss
  monitor: val_loss
  save_top_k: 1
  mode: min
  save_last: False
loss:
  name: SCELoss 
  params:
    alpha: 1 
    beta: 0.5